# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1c05e365bdf8570a69da69c77e3eb395b85db1b37c10fd314ec3404a91d3ec3dc51899e6657c31ef79be0011f0f5e4cbf292e20d334c5b3b6c6bf622986f296

test:
  secret_key_base: 7bf266bcbd8068b3d5a5712aaa9c49ec2ec165c8da12f8aa14500a5655a172f521582fe7a856e1947dd477b66432e2aaaacdc1685a215edc577b9a95f0be3089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
